<?php return array (
  'sans-serif' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'times-roman' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'courier' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'helvetica' => array(
    'normal' => $rootDir . '/lib/fonts/Helvetica',
    'bold' => $rootDir . '/lib/fonts/Helvetica-Bold',
    'italic' => $rootDir . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'zapfdingbats' => array(
    'normal' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold' => $rootDir . '/lib/fonts/ZapfDingbats',
    'italic' => $rootDir . '/lib/fonts/ZapfDingbats',
    'bold_italic' => $rootDir . '/lib/fonts/ZapfDingbats',
  ),
  'symbol' => array(
    'normal' => $rootDir . '/lib/fonts/Symbol',
    'bold' => $rootDir . '/lib/fonts/Symbol',
    'italic' => $rootDir . '/lib/fonts/Symbol',
    'bold_italic' => $rootDir . '/lib/fonts/Symbol',
  ),
  'serif' => array(
    'normal' => $rootDir . '/lib/fonts/Times-Roman',
    'bold' => $rootDir . '/lib/fonts/Times-Bold',
    'italic' => $rootDir . '/lib/fonts/Times-Italic',
    'bold_italic' => $rootDir . '/lib/fonts/Times-BoldItalic',
  ),
  'monospace' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'fixed' => array(
    'normal' => $rootDir . '/lib/fonts/Courier',
    'bold' => $rootDir . '/lib/fonts/Courier-Bold',
    'italic' => $rootDir . '/lib/fonts/Courier-Oblique',
    'bold_italic' => $rootDir . '/lib/fonts/Courier-BoldOblique',
  ),
  'dejavu sans' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSans-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSans-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSans-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSans',
  ),
  'dejavu sans mono' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSansMono-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSansMono-BoldOblique',
    'italic' => $rootDir . '/lib/fonts/DejaVuSansMono-Oblique',
    'normal' => $rootDir . '/lib/fonts/DejaVuSansMono',
  ),
  'dejavu serif' => array(
    'bold' => $rootDir . '/lib/fonts/DejaVuSerif-Bold',
    'bold_italic' => $rootDir . '/lib/fonts/DejaVuSerif-BoldItalic',
    'italic' => $rootDir . '/lib/fonts/DejaVuSerif-Italic',
    'normal' => $rootDir . '/lib/fonts/DejaVuSerif',
  ),
  'source sans pro' => array(
    '200' => $fontDir . '/source-sans-pro-200_0f1d90ee1e41fa500b5bdd010be93c25',
    '300' => $fontDir . '/source-sans-pro-300_302e2dc707bd747512a5d4b16bfd7a0f',
    'normal' => $fontDir . '/source-sans-pro-normal_9bbc93cd4eeb4c96ec714f118af1ef95',
    '600' => $fontDir . '/source-sans-pro-600_1ec5dd4a4563d5d2bc5b1f0210abb24b',
    'bold' => $fontDir . '/source-sans-pro-bold_3e55723bb0d4936b0320296623a8c224',
    '900' => $fontDir . '/source-sans-pro-900_d5c4039ece18917b2e9c878bd4f61b3f',
  ),
  'font awesome 5 brands' => array(
    'normal' => $fontDir . '/font-awesome-5-brands-normal_f4a4a9447985cb1910b69dbf0f0d7b61',
  ),
  'font awesome 5 free' => array(
    'normal' => $fontDir . '/font-awesome-5-free-normal_c275339c05c95773907749b24884139c',
    '900' => $fontDir . '/font-awesome-5-free-900_8ff56b27c16f383a8ecea805982abc49',
  ),
  'poppins' => array(
    '100' => $fontDir . '/poppins-100_561eceebd649a65d1ccc55bc682edf12',
    '200' => $fontDir . '/poppins-200_b2109dd5de087bd435b9f8ed89f19b52',
    '300' => $fontDir . '/poppins-300_5ede136950bbaadcad6ff55520449d10',
    'normal' => $fontDir . '/poppins-normal_80ae6e9e699d5e8597c6c0e47f0f703a',
    '500' => $fontDir . '/poppins-500_2da22e6c2e0f022b484da65536f67ae1',
    '600' => $fontDir . '/poppins-600_807dbf7c3a65547d000cd2ba47289c1e',
    'bold' => $fontDir . '/poppins-bold_2c9bca780e17bdd6ff9f14cbea4f600c',
    '800' => $fontDir . '/poppins-800_8bf7f931b6ef568af126b7b4dbf1434e',
    '900' => $fontDir . '/poppins-900_e74796abd27b11fff4443a1e46a187e1',
  ),
  'bree serif' => array(
    'normal' => $fontDir . '/bree-serif-normal_0424375025a2d61defa1a698e5ec494b',
  ),
  'roboto' => array(
    'normal' => $fontDir . '/roboto-normal_cf99a9d56c411ce3fa8a2fc49c520e74',
    'bold' => $fontDir . '/roboto-bold_1e996688829091a02d8ce32f4ce56696',
  ),
) ?>